import os

from PySide6 import QtWidgets, QtGui
from PySide6.QtCore import Qt, QEvent
from PySide6.QtGui import QKeyEvent
import substance_painter # type: ignore
import substance_painter.ui # type: ignore

from . import convert
from .penumbra import PenumbraClient
from .settings import Settings

penumbra = PenumbraClient()
script_dir = os.path.dirname(os.path.abspath(__file__))
settings = Settings(os.path.join(script_dir, "settings.json"))
metadata = substance_painter.project.Metadata("SubstanceToXIV")

XIVTEX_PLUGIN = None


def init_metadata():
    metadata.set("version", 1)
    metadata.set("mod_folder", "")
    metadata.set("move_tex", False)
    metadata.set("keep_dds", False)
    metadata.set("redraw", False)

    return "Project settings initialized."


def load_metadata():
    project_data = metadata.list()
    if not project_data:
        return init_metadata()
    else:
        return "Project settings loaded."


# def get_textools_button_text(self):
#     textools_path = settings.get("textools_path", "C:\Program Files\FFXIV TexTools")
#     if os.path.exists(textools_path):
#         self.TexToolsPath = textools_path
#         settings.set("textools_path", textools_path)
#         return f"TexTools path: {self.TexToolsPath}"
#     else:
#         self.TexToolsPath = None
#         return "TexTools not found, click here to set path..."


def init_enable_button(self):
    state = settings.get("textools_enable", True)
    settings.set("textools_enable", state)


def get_enable_button_text(self):
    enabled = settings.get("textools_enable", True)
    if enabled:
        return "Substance to XIV Enabled"
    else:
        return "Substance to XIV Disabled"


def get_textools_button_text(self):
    #  TODO: Improve this, separate button label logic from path validation and button initialization.
    textools_path = settings.get("textools_path", "C:/Program Files/FFXIV TexTools")
    console_tools = os.path.join(textools_path, "FFXIV_TexTools/ConsoleTools.exe")
    if os.path.exists(textools_path) and os.path.isfile(console_tools):
        self.TexToolsPath = textools_path
        settings.set("textools_path", textools_path)
        return f"TexTools Path\n'{self.TexToolsPath}'"
    else:
        self.TexToolsPath = None
        return "TexTools not found, click here to set path..."


class XIVTexPlugin:
    def __init__(self):
        # Init settings.
        init_enable_button(self)
        enable_button_text = get_enable_button_text(self)
        textools_button_text = get_textools_button_text(self)

        # Layout Elements.
        self.label_mainsettings = QtWidgets.QLabel("MAIN SETTINGS")
        self.button_enable = QtWidgets.QPushButton(enable_button_text)
        self.button_textools = QtWidgets.QPushButton(textools_button_text)
        self.checkbox_move_tex = QtWidgets.QCheckBox("Move TEX files to mod folder")
        self.checkbox_move_tex.setDisabled(True)
        self.checkbox_redraw = QtWidgets.QCheckBox("Force Penumbra redraw after export")
        self.checkbox_keep_dds = QtWidgets.QCheckBox("Keep DDS files")
        self.label_projectsettings = QtWidgets.QLabel("PROJECT SETTINGS")
        self.button_modfolder = QtWidgets.QPushButton("Click here to set a texture folder...")
        self.label_log = QtWidgets.QLabel("LOG")
        self.log = QtWidgets.QTextEdit()
        self.log.setReadOnly(True)
        self.log.setPlaceholderText("Log will be shown here...")
        self.button_quick_export = QtWidgets.QPushButton("Export")
        self.button_clear_log = QtWidgets.QPushButton("Clear Log")

        # Tooltips.
        self.button_textools.setToolTip("Set TexTools main directory, usually 'C:/Program Files/FFXIV TexTools'.")
        self.checkbox_move_tex.setToolTip("Enable moving of .TEX files, if disabled they will remain your project's export folder.")
        self.checkbox_redraw.setToolTip("This will try to get Penumbra to redraw after textures are exported. Make sure to enable 'Move TEX files to mod folder' for this to work.")
        self.checkbox_keep_dds.setToolTip("Keep DDS files generated by TexConv, usually not needed.")
        self.button_modfolder.setToolTip("Set a mod folder where .TEX files will be moved to after export.")
        self.button_quick_export.setToolTip("Open Export Textures window.")
        self.button_clear_log.setToolTip("Clear all log contents.")

        # Add elements to layout.
        layout = QtWidgets.QVBoxLayout()

        layout_main = QtWidgets.QVBoxLayout()
        layout_main.addWidget(self.label_mainsettings)
        layout_main.addWidget(self.button_enable)
        layout_main.addWidget(self.button_textools)
        layout_main.insertSpacing(3, 15)

        layout_project = QtWidgets.QVBoxLayout()
        layout_project.addWidget(self.label_projectsettings)
        layout_project.addWidget(self.button_modfolder)
        layout_project.addWidget(self.checkbox_move_tex)
        layout_project.addWidget(self.checkbox_redraw)
        layout_project.addWidget(self.checkbox_keep_dds)
        layout_project.insertSpacing(5, 15)
        layout_project.addWidget(self.label_log)
        layout_project.addWidget(self.log)

        layout_actions = QtWidgets.QHBoxLayout()
        layout_actions.addWidget(self.button_quick_export)
        layout_actions.addWidget(self.button_clear_log)

        layout.addLayout(layout_main)
        layout.addLayout(layout_project)
        layout.addLayout(layout_actions)

        # Hook layout to Substance Painter.
        self.window = QtWidgets.QWidget()
        self.window.setLayout(layout)
        self.window.setWindowTitle("Substance to XIV v1.0")
        self.window.setWindowIcon(QtGui.QIcon(os.path.join(os.path.dirname(__file__), "icon.png")))
        substance_painter.ui.add_dock_widget(self.window)

        # Handle click events.
        self.button_enable.clicked.connect(self.button_enable_click)
        self.button_textools.clicked.connect(self.button_textools_click)
        self.checkbox_move_tex.clicked.connect(self.checkbox_move_tex_click)
        self.checkbox_keep_dds.clicked.connect(self.checkbox_keep_dds_click)
        self.checkbox_redraw.clicked.connect(self.checkbox_redraw_click)
        self.button_modfolder.clicked.connect(self.button_modfolder_click)
        self.button_quick_export.clicked.connect(self.button_quick_export_click)
        self.button_clear_log.clicked.connect(self.button_clear_log_click)

        # Subscribe to project related events.
        connections = {
            substance_painter.event.ProjectOpened: self.on_project_opened,
            substance_painter.event.ProjectCreated: self.on_project_created,
            substance_painter.event.ExportTexturesEnded: self.on_export_textures_ended,
        }
        for event, callback in connections.items():
            substance_painter.event.DISPATCHER.connect(event, callback)

    def button_enable_click(self):
        state = not settings.get("textools_enable")
        settings.set("textools_enable", state)
        self.button_enable.setText(get_enable_button_text(self))

    def button_textools_click(self):
        if self.TexToolsPath is not None and os.path.exists(self.TexToolsPath):
            path = self.TexToolsPath
        else:
            # TODO: Test this.
            path = "C:/Program Files"

        path = QtWidgets.QFileDialog.getExistingDirectory(
            substance_painter.ui.get_main_window(),
            "Set TexTools Main Directory",
            path
        )

        if path != "":
            settings.set("textools_path", path)
            self.TexToolsPath = path

            textools_button_text = get_textools_button_text(self)
            self.button_textools.setText(textools_button_text)
            self.log.append(f"Textools path: '{self.TexToolsPath}'")

    def checkbox_move_tex_click(self):
        state = metadata.get("move_tex")
        metadata.set("move_tex", not state)

    def checkbox_redraw_click(self):
        state = metadata.get("redraw")
        metadata.set("redraw", not state)

    def checkbox_keep_dds_click(self):
        state = metadata.get("keep_dds")
        metadata.set("keep_dds", not state)

    def button_modfolder_click(self):
        starting_path = metadata.get("mod_folder")
        if starting_path == "":
            starting_path = penumbra.mod_directory()
        if starting_path == "":
            starting_path = "C:\\"

        path = QtWidgets.QFileDialog.getExistingDirectory(
            substance_painter.ui.get_main_window(),
            "Set Mod Textures Folder",
            starting_path
        )

        if path != "":
            metadata.set("mod_folder", path)
            self.update_ui()

            # textools_path_label = self.TexToolsPath
            self.log.append(f"Mod texture folder: '{path}'")

        self.update_ui()

    def button_quick_export_click(self):
        if not substance_painter.project.is_open():
            self.log.append("No project open!")
            return

        event = QKeyEvent(QEvent.KeyPress, Qt.Key_E, Qt.ControlModifier | Qt.ShiftModifier)
        QtWidgets.QApplication.sendEvent(substance_painter.ui.get_main_window(), event)

        # js_code = 'alg.mapexport.getProjectExportPreset()'
        # baking_parameters = substance_painter.js.evaluate(js_code)
        # self.log.append(str(baking_parameters))
        # ---> resource://your_assets/ATSU XIV Normal Mask Custom AO?version=9846787643662974824.spexp

        #  Generate an export JSON config like in file:///C:/Program%20Files/Adobe/Adobe%20Substance%203D%20Painter/resources/python-doc/substance_painter/export.html#substance_painter.export.list_project_textures
        #  and use the current export preset to export the project.
        #  Will need to set an export directory and get the active texture set with file:///C:/Program%20Files/Adobe/Adobe%20Substance%203D%20Painter/resources/python-doc/substance_painter/textureset/index.html#substance_painter.textureset.get_active_stack
        #  Will also need to add an option to get all texture sets and export all.

    def button_clear_log_click(self):
        self.log.clear()

    def update_ui(self):
        self.checkbox_move_tex.setChecked(metadata.get("move_tex"))
        self.checkbox_keep_dds.setChecked(metadata.get("keep_dds"))
        mod_folder = metadata.get("mod_folder")
        if mod_folder == "":
            mod_folder = "Click here to set a texture folder..."
            self.checkbox_move_tex.setDisabled(True)
            self.checkbox_move_tex.setChecked(False)
        else:
            mod_folder = mod_folder[-45:][mod_folder.find('/'):]
            mod_folder = f"Mod folder\n'.../{mod_folder}'"
            self.checkbox_move_tex.setDisabled(False)
        self.button_modfolder.setText(mod_folder)

    def __del__(self):
        # Remove all added UI elements.
        substance_painter.ui.delete_ui_element(self.log)

    def on_project_opened(self, e):
        self.log.append(f"Project '{substance_painter.project.name()}' opened.")
        result = load_metadata()
        self.log.append(result)
        self.update_ui()

    def on_project_created(self, e):
        self.log.append(f"Project '{substance_painter.project.name()}' created.")
        result = init_metadata()
        self.log.append(result)
        self.update_ui()

    def on_export_textures_ended(self, res):
        enabled = settings.get("textools_enable")
        if not enabled:
            self.log.append("Plugin disabled, ignoring export.")
            return

        self.log.append(res.message)
        for file_list in res.textures.values():
            for file_path in file_list:

                dds = convert.to_dds(file_path, settings.get("textools_path"))
                self.log.append(f"Created: {os.path.basename(dds)}")

                tex = convert.to_tex(file_path, settings.get("textools_path"))
                self.log.append(f"Created: {os.path.basename(tex)}")

                if not metadata.get("keep_dds"):
                    os.remove(dds)
                    self.log.append(f"Deleted: {os.path.basename(dds)}")

        self.log.append("All done, attempting Penumbra redraw...")
        redraw = penumbra.redraw_self()
        self.log.append(redraw)


def start_plugin():
    """This method is called when the plugin is started."""
    global XIVTEX_PLUGIN
    XIVTEX_PLUGIN = XIVTexPlugin()


def close_plugin():
    """This method is called when the plugin is stopped."""
    global XIVTEX_PLUGIN
    del XIVTEX_PLUGIN


if __name__ == "__main__":
    start_plugin()
